### PR TITLE
Added back to top button on all pages

### LINKED ISSUE #63: Add back to top button on all pages
Assign me this issue under JWoC 2024

### PR DESCRIPTION
**Pull request by Sanglap-Halder**
# Title and Issue number 
Title : Add back to top button on all pages

Issue No. : #63

Close #63 

## Changes Made
Added back to top button on all pages

## Screenshots (if applicable)
[Include any relevant screenshots or images to support your changes.]

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding standards.
- [ ] I have updated the documentation (if necessary).
- [x] I have read the contributing guidelines.

### CODE REVIEW

**Comment by Sanglap-Halder** [comment]
I have done this project under JWoC 2024

**Comment by JiyaGupta-cs** [comment]
@Sanglap-Halder It is present at the bottom of the page and is visible only if I scroll to the last of the page
Scroll to top buttons are visible after scrolling a certain portion of the website

**Comment by Sanglap-Halder** [comment]
I will solve it

**Comment by Sanglap-Halder** [comment]
Please check it

**Comment by JiyaGupta-cs** [comment]
Adjust the width of it, it is being skewed now
It should appear after scrolling down a bit , not from the extreme top of the page

**Comment by JiyaGupta-cs** [comment]
@Sanglap-Halder any update?

**Comment by Sanglap-Halder** [comment]
Give a few time I will do it

**Comment by Sanglap-Halder** [comment]
Please merge this in this state

**Comment by JiyaGupta-cs** [comment]
@Sanglap-Halder 
Don't feel low, you can do it
https://www.npmjs.com/package/react-scroll-to-top
Take reference from this
And if you need any further help you can ping me

**Pull request closed without merging**
