### PR TITLE
fixed alignment

### LINKED ISSUE #177: fixing alignment of reviews with stars
## Issue Description
image

The number is not in alignment and looks off with the stars, I want to fix that.

Please assign me this as part of GSSOC'24

### PR DESCRIPTION
**Pull request by sakshii00**
# Title and Issue number 
Title : Fixed alignment of stars with number

Issue No. : 177

Closes #177 

## Changes Made
I fixed alignment for both light and dark mode and now it seems fine.

### Before
image

### After
**in dark mode**
image
**in light mode**
image

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding standards.
- [x] I have updated the documentation (if necessary).
- [x] I have read the contributing guidelines.

### CODE REVIEW

**Comment by sakshii00** [comment]
@ivedmohan can you please review and merge this

**Comment by ivedmohan** [comment]
> @ivedmohan can you please review and merge this

@sakshii00 can you also mention issue no. also.

**Comment by sakshii00** [comment]
> > @ivedmohan can you please review and merge this
> 
> @sakshii00 can you also mention issue no. also.

the issue number is #177

**Comment by sakshii00** [comment]
@ivedmohan can you please review this now?

**Review by ivedmohan — APPROVED** [review]

**Comment by sakshii00** [comment]
@Sushilverma002 @Vansh-Choudhary can either of you please review and let me know if any further changes are required?

**Comment by sakshii00** [comment]
@Vansh-Choudhary could you please check this one out?

**Review by Sushilverma002 — APPROVED** [review]
approved

**Comment by sakshii00** [comment]
@Sushilverma002 can you please assign the PR to me so it can be counted?

**Pull request merged**
