### PR TITLE
Create Explore More Button On Women, Men Products

### PR DESCRIPTION
**Pull request by swetasingh8844**
I have added More Products to the Women and Men Products and all are display in sets of 12 every time when user clicks on the Explore More Button.
I have 20 products in men and Women section . In both section firstly it shows the 12 products and on clicking Explore More Button the remaining 8 products are shown .
The page are looks like:-
image
image
In the same way the women section looks like.

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
Good Job @swetasingh8844 !!!
Could you add one more thing to it
It should display more products without removing the earlier ones
means below them

**Comment by swetasingh8844** [comment]
ok i'll add some more products to it

**Comment by swetasingh8844** [comment]
@JiyaGupta-cs  please have a look

**Comment by swetasingh8844** [comment]
@JiyaGupta-cs I have added the products . please have a look

**Comment by JiyaGupta-cs** [comment]
@swetasingh8844 You didn't get my point
I asked that the earlier products should not get removed 
The new ones should be displayed below it

**Comment by swetasingh8844** [comment]
okk i get it

**Comment by swetasingh8844** [comment]
image

**Comment by JiyaGupta-cs** [comment]
What have you changed
I can't figure it out

**Comment by swetasingh8844** [comment]
Earlier only few products are there, now all the products are added
image

**Comment by JiyaGupta-cs** [comment]
@swetasingh8844 
1. All the checks have failed
2. Could you add one more thing to it
It should display more products without removing the earlier ones
means below them
I asked this to you
I think you haven't understood it

**Pull request closed without merging**
