### PR TITLE
Enhancement: Implement Customized Scrollbar (#28)

### LINKED ISSUE #28: Enhancement: Implement Customized Scrollbar.
**Description:**
Enhance the visual appeal of our website by implementing a customized scrollbar. 

**Proposed Changes**
Customize the scrollbar appearance to match our website's theme.
Ensure the scrollbar is sleek and does not occupy unnecessary space.

### **Screenshots:**
**Current scrollbar:**
Screenshot 2024-01-20 203030
**Working under JWoC'24**

### PR DESCRIPTION
**Pull request by ramith-kulal**
## Description:
Enhance the visual appeal of our website by implementing a customized scrollbar.
Fix #28 
## Proposed Changes:
- Customize the scrollbar appearance to match our website's theme.
- Ensure the scrollbar is sleek and does not occupy unnecessary space.

## Screenshots:
Screenshot 2024-01-30 001302
**Working under JWoC'24**

### CODE REVIEW

**Comment by ramith-kulal** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **shop-nex**	✅ Ready ([Inspect](https://vercel.com/jiyagupta-cs-projects/shop-nex/AQGSZDPrGtJoYB8SeYvAGZ61DvC8))	[Visit Preview](https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)	💬 [**Add feedback**](https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-feedback-link)	Jan 29, 2024 6:49pm

well  its working fine in the preview i guess https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

**Comment by JiyaGupta-cs** [comment]
> > **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> > Name	Status	Preview	Comments	Updated (UTC)
> > **shop-nex**	✅ Ready ([Inspect](https://vercel.com/jiyagupta-cs-projects/shop-nex/AQGSZDPrGtJoYB8SeYvAGZ61DvC8))	[Visit Preview](https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)	💬 [**Add feedback**](https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-feedback-link)	Jan 29, 2024 6:49pm
> 
> well its working fine in the preview i guess https://vercel.live/open-feedback/shop-nex-git-fork-ramith-kulal-fea-d5d762-jiyagupta-cs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

not working on this link

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Maybe the difference is due to different web browsers , so fix it for all browsers

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal LGTM

**Pull request merged**
