### PR TITLE
Fixed footer logo link

### LINKED ISSUE #279: Footer Logo Not Redirecting to Home Page
## Issue Description
Clicking on the logo in the footer section does not lead to the home page. The logo is not functioning as a link.

## Steps to Reproduce
1. Go to the [website](https://shopnex.vercel.app/).
2. Scroll down to the footer section.
3. Click on the logo in the footer.

## Expected Behavior
The logo in the footer should function as a link to the home page. When clicked, it should redirect the user to the home page of the website.

## Actual Behavior
Nothing happens when the logo in the footer section is clicked. It does not redirect the user to the home page.

## Screenshots
image

Please assign me this issue. I am a contributor for GSSoC’ 24. I would love to work on this issue.

### PR DESCRIPTION
**Pull request by PranavKeshav24**
# Footer logo link is fixed, #279  
Title : Footer logo link fixed

Issue No. : 
Close #279 

## Changes Made
Added the link to the ShopNex icon in the footer to redirect to the 'Shop' page when clicked,

## Screenshots
image

## Checklist
- [✔] I have tested these changes locally.
- [✔] I have reviewed the code and ensured it follows the project's coding standards.
- [✔] I have updated the documentation (if necessary).
- [✔] I have read the contributing guidelines.

Please review my PR and let me know if any changes are required.

### CODE REVIEW

**Review by Vansh-Choudhary — APPROVED** [review]
Perfect! Approved.

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Thank you so much for the opportunity :)!

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Could you please add the GSSoC and the level tags to this as well?

**Review by Sushilverma002 — APPROVED** [review]

**Comment by PranavKeshav24** [comment]
@Sushilverma002 @Vansh-Choudhary 
I see that this PR has been approved, could you please verify and merge it?

**Pull request merged**
