### PR TITLE
Made website Responsive

### LINKED ISSUE #504: Making website responsive
I would like to make the website responsive 

Please assign this issue to me
@JiyaGupta-cs

### PR DESCRIPTION
**Pull request by dhairyagothi**
# Title and Issue number 
Title : Made website responsive 

Issue No. : #504 

Close #504 

## Changes Made
made website responsive 

## Screenshots (if applicable)

https://github.com/JiyaGupta-cs/ShopNex/assets/142989448/00c1fdfb-ebe4-4651-bc5f-56cfda78efca

## Checklist
- [X] I have tested these changes locally.
- [X] I have reviewed the code and ensured it follows the project's coding standards.
- [X] I have updated the documentation (if necessary).
- [X] I have read the contributing guidelines.

Please check the PR and merge it asap with gssoc badge and please level 3 😢

### CODE REVIEW

**Comment by dhairyagothi** [comment]
please merge this PR @JiyaGupta-cs

**Comment by dhairyagothi** [comment]
@JiyaGupta-cs mam please  merge this PR

**Comment by dhairyagothi** [comment]
@JiyaGupta-cs please mam merge the PR

**Comment by dhairyagothi** [comment]
@JiyaGupta-cs mam please merge the PR

**Comment by Sushilverma002** [comment]
it's properly responsive @dhairyagothi

**Comment by dhairyagothi** [comment]
> it's properly responsive @dhairyagothi

what ?? i have made it responsive before it is not

**Comment by dhairyagothi** [comment]
mobile view before 
image

**Comment by Sushilverma002** [comment]
check your deployment on the vercel. you will find your answer.

**Comment by dhairyagothi** [comment]
> check your deployment on the vercel. you will find your answer.



@Sushilverma002 
shopnex.vercel.app
Check current deployment in your mobile 

And check my PR in your mobile view 

You will get difference 

Before closing a PR see once what is the issue
And PR is not merged from last 3 weeks 
I have done a lot of work to make it correct and you just closed the issue 
How good it is

**Pull request closed without merging**
