### PR TITLE
Fix : Implement Dynamic Price Calculation in CartItems

### LINKED ISSUE #85: BUG: Cart Total Sum Calculation
## Issue Description

The total sum of cart items is not adding up correctly. Additionally, there are some other problems present in the cart functionality.
## Steps to Reproduce

Add multiple items to the cart.
Navigate to the cart page.
Review the total sum displayed.
## Expected Behavior

The total sum displayed in the cart should accurately reflect the combined prices of all items added to the cart.
## Actual Behavior

The total sum displayed in the cart does not accurately reflect the combined prices of all items added to the cart. Some items may not be included in the total, or the total sum may be incorrect.
## Screenshots

Screenshot 2024-02-21 110017
**Working under JWOC**

### PR DESCRIPTION
**Pull request by ramith-kulal**
# Title and Issue number 
Title : Resolving Issues regarding Cart section.

Issue No. : #85 
Close #85 

This pull request introduces dynamic price calculation in the CartItems component to accurately reflect the total price based on the quantity of each item in the shopping cart. Previously, the price displayed was static and did not consider the quantity of each item.
## Changes Made
- Added a new function calculateTotalPrice in the CartItems component to compute the total price for each item based on its - quantity and price.
- Updated the rendering logic to display the total price for each item dynamically.
- Adjusted the getTotalCartAmount function in the ShopContextProvider to properly calculate the total cart amount by summing up the prices of all items considering their quantities.

These changes ensure that the subtotal and total prices in the cart are accurately calculated, taking into account the quantity of each item. This enhances the user experience by providing a more realistic representation of the shopping cart contents and the total cost.
[List the specific changes made in this pull request.]

## Screenshots (if applicable)
[Include any relevant screenshots or images to support your changes.]

Screenshot 2024-02-21 120417
Screenshot 2024-02-21 120359

## Checklist
- [X] I have tested these changes locally.
- [X] I have reviewed the code and ensured it follows the project's coding standards.
- [ ] I have updated the documentation (if necessary).
- [X] I have read the contributing guidelines.
- **working under jwoc**

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal  
image
you need to multiply the quantity with price also

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Make one more PR

**Comment by JiyaGupta-cs** [comment]
Oh fine
I got confused 
No problem
I'll merge it

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal 
See , are your points rewarded , check in the leaderboard

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal 
Open a new issue for changing the position of submit button
I'll assign you there also

**Comment by ramith-kulal** [comment]
> @ramith-kulal Open a new issue for changing the position of submit button I'll assign you there also

got you.

**Pull request merged**
