### PR TITLE
fixed quantity visibility issue

### PR DESCRIPTION
**Pull request by Bishal-35**

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@Bishal-35 figure out why checks are failing , fix it and commit only the required file not package.json unnecessarily until it's required

**Comment by JiyaGupta-cs** [comment]
And mention the issue number and also attach screenshots of before and after

**Comment by Bishal-35** [comment]
where should i mention it

**Comment by JiyaGupta-cs** [comment]
Here itself using #

**Comment by Bishal-35** [comment]
# Pull request for quantity visibility issue



## Issue No: 

#60 




# Screenshots 📷


## Before fixing

before_fix

## After fixing

after_fix

**Comment by JiyaGupta-cs** [comment]
Have you restored package.json ?

**Comment by Bishal-35** [comment]
Yes, I have restored it

**Comment by JiyaGupta-cs** [comment]
@Bishal-35 I can see many changes
Check files changed section

**Comment by Bishal-35** [comment]
@JiyaGupta-cs check if it is okay now

**Pull request merged**
