### PR TITLE
Fixed the footer logo redirection.

### LINKED ISSUE #279: Footer Logo Not Redirecting to Home Page
## Issue Description
Clicking on the logo in the footer section does not lead to the home page. The logo is not functioning as a link.

## Steps to Reproduce
1. Go to the [website](https://shopnex.vercel.app/).
2. Scroll down to the footer section.
3. Click on the logo in the footer.

## Expected Behavior
The logo in the footer should function as a link to the home page. When clicked, it should redirect the user to the home page of the website.

## Actual Behavior
Nothing happens when the logo in the footer section is clicked. It does not redirect the user to the home page.

## Screenshots
image

Please assign me this issue. I am a contributor for GSSoC’ 24. I would love to work on this issue.

### PR DESCRIPTION
**Pull request by PranavKeshav24**
# Title and Issue number 
Title : Fixed the footer logo redirection.

Issue No. :
Close #279 

## Changes Made
Added the link to the ShopNex icon in the footer to redirect to the homepage when clicked,

## Checklist
- [✔] I have tested these changes locally.
- [✔] I have reviewed the code and ensured it follows the project's coding standards.
- [✔] I have updated the documentation (if necessary).
- [✔] I have read the contributing guidelines.

### CODE REVIEW

**Comment by Vansh-Choudhary** [comment]
I see you have added the link but I'm not able to click the logo and then being redirect to the home page.

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Please navigate to a different section such as men, women or kids and then try clicking on the logo in the footer. It will then take the user to the homepage.

**Comment by Vansh-Choudhary** [comment]
@PranavKeshav24 works sometimes, mostly does not work even on sections like men and women. Also make it work on shop section and create a new PR.

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Thank you reviewing my PR! I will work on the changes and create a new PR.

**Pull request closed without merging**
