### PR TITLE
Conflict Resolve

### PR DESCRIPTION
**Pull request by prasukjain07**

### CODE REVIEW

**Comment by prasukjain07** [comment]
@JiyaGupta-cs please check
I resolve the conflict

**Comment by JiyaGupta-cs** [comment]
image

Please style it @prasukjain07

**Comment by prasukjain07** [comment]
@JiyaGupta-cs please check

**Comment by JiyaGupta-cs** [comment]
@prasukjain07 Mention the issue which you closed

**Comment by prasukjain07** [comment]
@JiyaGupta-cs I closed issue #5 please give points of it to me

**Pull request merged**
