### PR TITLE
Resolved the Email Validation problem

### PR DESCRIPTION
**Pull request by Amruta7203**
# Title and Issue number 
Title : Resolved the email validation problem

Issue No. : #244 

Close #244 

## Changes Made
This pull request addresses the freezing input field issue in the newsletter subscription form when entering invalid email addresses.

## Screenshots (if applicable)
[Recorder.webm](https://github.com/JiyaGupta-cs/ShopNex/assets/116087736/060dc294-92b1-4c02-9134-7089cf9536db)

## Checklist
-  I have tested these changes locally.
-  I have reviewed the code and ensured it follows the project's coding standards.
-  I have updated the documentation (if necessary).
-  I have read the contributing guidelines.

### CODE REVIEW

**Comment by Amruta7203** [comment]
@Vansh-Choudhary Resolved the problem of freezing input value. Kindly review this pull request and add Gssoc labels.

**Review by Vansh-Choudhary — APPROVED** [review]
@Amruta7203 Good work. Approved !

**Comment by Amruta7203** [comment]
Thank you @Vansh-Choudhary!

**Comment by Amruta7203** [comment]
Hello @Vansh-Choudhary Pls merge this PR.

**Comment by Amruta7203** [comment]
Hello @Vansh-Choudhary Pls merge this PR.

**Comment by Amruta7203** [comment]
Hello @Vansh-Choudhary Pls merge this PR.

**Pull request merged**
