### PR TITLE
Fix: submit button

### LINKED ISSUE #88: BUG: Alignment of Submit Button
## Issue Description
[Provide a brief description of the issue]
Submit button of promocode in checkout page needs to be aligned properly.

## Expected Behavior

The button needs to be properly aligned.

## Screenshots
[Include any relevant screenshots]
Screenshot 2024-02-21 125330

**working under jwoc**

### PR DESCRIPTION
**Pull request by ramith-kulal**
# Title and Issue number 
Title : Fix submit button

Issue No. : #88  

Close #88 

## Changes Made
[List the specific changes made in this pull request.]
changed the position of submit button.
## Screenshots (if applicable)
[Include any relevant screenshots or images to support your changes.]

## Checklist
- [X] I have tested these changes locally.
- [X] I have reviewed the code and ensured it follows the project's coding standards.
- [X] I have updated the documentation (if necessary).
- [X] I have read the contributing guidelines.
working under jwoc

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal 
Make it like this
It's requires just a single line change
image

**Comment by ramith-kulal** [comment]
> @ramith-kulal Make it like this It's requires just a single line change image

Screenshot 2024-02-21 134713
just a humble request this one looks more appealing ig  , if still the requirement is same as you have shown i would change that.

**Comment by JiyaGupta-cs** [comment]
No
Make it as a sent the screenshot
Because if we place it above then the page will look empty

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal LGTM

**Pull request merged**
