### PR TITLE
hover effect added

### PR DESCRIPTION
**Pull request by singhcodes26**
I have added the hovering effects on the icons. However I the images are not compatible with the effects , like it's not looking so good. Do let me know if I have to change the images.
#6

### CODE REVIEW

**Comment by JiyaGupta-cs** [comment]
@singhcodes26 Attach the video of what you have changed and also link the issue number which it closes

**Comment by singhcodes26** [comment]
here's the attached video:

https://github.com/JiyaGupta-cs/ShopNex/assets/88542318/485c7e9a-c97e-41fe-9aba-d6f99a9ef85d

**Comment by JiyaGupta-cs** [comment]
@singhcodes26 Only it's height is getting changed , width is not changing due to which the logo elongates , fix it

**Comment by JiyaGupta-cs** [comment]
@singhcodes26 Any update?

**Comment by singhcodes26** [comment]
> @singhcodes26 Any update?

I will complete it by today

**Comment by singhcodes26** [comment]
I have made height and width adjustments to the hover effect . 

https://github.com/JiyaGupta-cs/ShopNex/assets/88542318/89ab9955-1480-4a7a-9c4e-4b67ac3aa02d

**Comment by JiyaGupta-cs** [comment]
@singhcodes26 Resolve the conflicts

**Comment by singhcodes26** [comment]
@JiyaGupta-cs issues resolved

**Pull request merged**
