### PR TITLE
Added the review section component to the product page.

### LINKED ISSUE #276: Enhancement: Add a Review Section for Product Ratings and Reviews
## Issue Description
There is currently no section on the product page for displaying ratings and reviews of the product. This feature is important for providing feedback from customers who have purchased and used the product.

## Steps to Reproduce
1. Go to the [website](https://shopnex.vercel.app/).
2. Navigate to any product page.
3. Notice that there is no section for displaying product ratings and reviews.

## Expected Behavior
There should be a review section on each product page where users can see the ratings and reviews of the product. This section should display the average rating of the product and a list of reviews from customers.

## Actual Behavior
There is currently no review section on the product page. Users cannot see the ratings and reviews of the product.

## Screenshots
image

Please assign me this issue. I am a contributor for GSSoC’ 24. I would love to work on this issue.

### PR DESCRIPTION
**Pull request by PranavKeshav24**
# Added Review Section to Product Page, #276 
Title : Added Review Section to Product Page

Issue No. : 

Close #276

## Changes Made
1. Created the ReviewSection.jsx component which renders user review section from an array of objects.
2. Utilised the 'react-icons' package to display the star ratings.
3. Applied styles using ReviewSection.css component.

## Screenshots 
image

## Checklist
- [✔] I have tested these changes locally.
- [✔] I have reviewed the code and ensured it follows the project's coding standards.
- [✔] I have updated the documentation (if necessary).
- [✔] I have read the contributing guidelines.

Please review my PR and let me know if any changes are required. Thank you.

### CODE REVIEW

**Review by Vansh-Choudhary — APPROVED** [review]
Good work bro! Approved.

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Thank you so much! I would love to contribute more towards the project!

**Comment by Vansh-Choudhary** [comment]
Sure! tag me on issues and I'll assign you 2 more issues.

**Comment by PranavKeshav24** [comment]
@Vansh-Choudhary Sure, thanks 😃!

**Comment by Anmolgupta2004** [comment]
can you please assign to me that issue?

**Comment by PranavKeshav24** [comment]
@Sushilverma002 Could you please review this PR and approve it if everything looks good?

**Comment by lovelymahor** [comment]
can you please assign to me that issue?

**Review by Sushilverma002 — APPROVED** [review]

**Pull request merged**
