### PR TITLE
Added route

### LINKED ISSUE #295: BUG: Buttons are dummy on home screen
@JiyaGupta-cs 
## Issue Description
[Provide a brief description of the issue]
- when we click on banner button or explore buttons there is nothing happen

## Steps to Reproduce
[Outline the steps required to reproduce the issue]
- we can create another route or seperate page for particular button

## Expected Behavior
[Describe what you expected to happen]
- we can redirect to explore page 

## Actual Behavior
[Describe what actually happened]
- nothing happen when i click on "explore now" button

## Screenshots
[Include any relevant screenshots]
image

### PR DESCRIPTION
**Pull request by dhruv8433**
# Title and Issue number 
Title :
BUG: Buttons are dummy on home screen #295

Issue No. :
#295

Close #295

## Changes Made
[List the specific changes made in this pull request.]
- added 2 routes on button click user will be redirect on this paths
    `/collections`
     `/offers`

## Screenshots (if applicable)
[Include any relevant screenshots or images to support your changes.]
1. collection route
image

2. offers route
image

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding standards.
- [x] I have updated the documentation (if necessary).
- [x] I have read the contributing guidelines.

### CODE REVIEW

**Comment by dhruv8433** [comment]
@JiyaGupta-cs  Please check this and merge it

**Comment by Vansh-Choudhary** [comment]
approved !

**Review by Vansh-Choudhary — APPROVED** [review]
approved !

**Review by Sushilverma002 — APPROVED** [review]

**Comment by dhruv8433** [comment]
thank you for approvel

**Pull request merged**
