### PR TITLE
Added Responsivess

### PR DESCRIPTION
**Pull request by Prithwi32**
https://github.com/JiyaGupta-cs/ShopNex/assets/115262737/c35cc1fd-8c85-4feb-b0da-f41eb88caa85

-Made website reponsive for iphone, tabs etc.
-Made changes to
        modified:   src/Components/CartItems/CartItems.css
        modified:   src/Components/Footer/Footer.css
        modified:   src/Components/Hero/Hero.css
        modified:   src/Components/Hero/Hero.jsx
        modified:   src/Components/Navbar/Navbar.css
        modified:   src/Components/Navbar/Navbar.jsx
        modified:   src/Components/NewCollections/NewCollections.css
        modified:   src/Components/NewsLetter/NewsLetter.css
        modified:   src/Components/Offers/Offers.css
        modified:   src/Components/Popular/Popular.css
        modified:   src/Pages/CSS/LoginSignup.css
        modified:   src/Pages/CSS/ShopCategory.css

### CODE REVIEW

**Comment by Prithwi32** [comment]
Issue: Responsiveness #1 
@JiyaGupta-cs  Please review it and let me know the feedback

**Comment by Prithwi32** [comment]
> @Prithwi32 Good Job!!! Please make the navbar also responsive Make a navbar for mobile view In it keep all the sections of Home Men Women Kids etc. closed in it And Cart and ShopNex Logo as it is

@JiyaGupta-cs actually it's responve now...do you mean I need to add dropdown menu?

**Comment by Prithwi32** [comment]
> @Prithwi32 Like this image

Okay I will work on this...either hamburger menu / side bar I will implement

**Comment by Prithwi32** [comment]
> @Prithwi32 Go ahead and make it for mobile only Don't change it for desktop view.

Okay thank you 😊

**Comment by Prithwi32** [comment]
> image
> 
> -- After clickling hamburger menu image

@JiyaGupta-cs  Please could you check this once now

**Comment by Prithwi32** [comment]
@JiyaGupta-cs  And I'm contributing under JWOC'24

**Comment by Prithwi32** [comment]
> @JiyaGupta-cs And I'm contributing under JWOC'24

@JiyaGupta-cs Please could you checkout this PR...It's 4 days past

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 
It looks good to me
Please resolve the conflicts to merge

**Comment by Prithwi32** [comment]
> @Prithwi32 It looks good to me Please resolve the conflicts to merge

@JiyaGupta-cs could you check it now, conflicts were resolved

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 
Resolve 
image

**Comment by Prithwi32** [comment]
> @Prithwi32 Resolve image

Actually 2 times I resolved confilts before,.. since you are merging others PRs it's leading to confils to my PR

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 Today I have not merged any other PR, it still has errors

**Comment by Prithwi32** [comment]
> @Prithwi32 Today I have not merged any other PR, it still has errors

It's okay...I will do again..

**Comment by Prithwi32** [comment]
@JiyaGupta-cs hello could you check it once now?

**Comment by Prithwi32** [comment]
@JiyaGupta-cs please could you review my PR?

**Comment by JiyaGupta-cs** [comment]
Figure out why checks are failing
Then I'll merge it by tomorrow

**Comment by JiyaGupta-cs** [comment]
Screenshot_20240216_181608

@Prithwi32 fix this then I will merge it asap

**Comment by Prithwi32** [comment]
> Screenshot_20240216_181608
> 
> @Prithwi32 fix this then I will merge it asap

okay

**Comment by Prithwi32** [comment]
@JiyaGupta-cs I have fixed the issues...please could you check once now

**Pull request merged**
