### PR TITLE
Collection page

### LINKED ISSUE #310: FEAT: Add Collection Page
@JiyaGupta-cs 
## Issue Description
[Provide a brief description of the issue]
- we can add collections page where user can explore and buy 
- when user click "Latest Collection" button we'll redirect user to `/collections` and there user can explore

## Steps to Reproduce
[Outline the steps required to reproduce the issue]
- create a new page or route for latest collection 

## Screenshots
[Include any relevant screenshots]

something like this

image

### PR DESCRIPTION
**Pull request by dhruv8433**
@JiyaGupta-cs  @Vansh-Choudhary  Please check this and merge it

# Title and Issue number 
Title :
FEAT: Add Collection Page #310
Issue No. :
#310

Close #310

## Changes Made
[List the specific changes made in this pull request.]
- added collections page 
- when user click on latest collection they will redirect here

## Screenshots (if applicable)
[Include any relevant screenshots or images to support your changes.]

- without any filter
image

- for mens 
image

- for womens 
image

- price high to low
image

- category t-shirt
image

## Checklist
- [x] I have tested these changes locally.
- [x] I have reviewed the code and ensured it follows the project's coding standards.
- [x] I have updated the documentation (if necessary).
- [x] I have read the contributing guidelines.

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Vansh-Choudhary please tell me if you need any kind of changes

**Comment by dhruv8433** [comment]
Hey @JiyaGupta-cs ,
i completed my issue about collection page design and filtering the category like low to high price ,...
now ready to merged and improve your website

**Comment by dhruv8433** [comment]
@Vansh-Choudhary please check this and merge it

**Comment by dhruv8433** [comment]
@JiyaGupta-cs 
@Vansh-Choudhary 

as you say, i designed collection page
kindly please check it and merge it

**Comment by dhruv8433** [comment]
@Vansh-Choudhary 

@JiyaGupta-cs 

please response 
merge this pr and please add level lable

**Comment by dhruv8433** [comment]
@Vansh-Choudhary

@JiyaGupta-cs

please response
merge this pr and please add level label

**Comment by Vansh-Choudhary** [comment]
@dhruv8433 make the cards look same as the cards in the men women section, we cannot add different kind of cards. The design should be constant throughout the website.

**Comment by dhruv8433** [comment]
@Vansh-Choudhary 

now you can check this and merge it 
i update styling 

image

**Comment by dhruv8433** [comment]
@Vansh-Choudhary 

please merge this and also add level

**Comment by dhruv8433** [comment]
@Vansh-Choudhary 

please merge this and 
### also add level 3
i applied all fiters

- based on categorys
- based on details
- based on clothing
- based on pricing

**Comment by dhruv8433** [comment]
@Vansh-Choudhary

please merge this and

also add level 3
i applied all fiters

based on categorys
based on details
based on clothing
based on pricing

**Comment by dhruv8433** [comment]
@Vansh-Choudhary

please merge this and

also add level 3
i applied all fiters

based on categorys
based on details
based on clothing
based on pricing

**Pull request closed without merging**
