### PR TITLE
Created latest collection page

### PR DESCRIPTION
**Pull request by Bishal-35**
Latest collection page created

### CODE REVIEW

**Comment by Bishal-35** [comment]
> @Bishal-35 Why is it empty?

Didn't added anything..
Please describe what types of products to be added like men and women only?

**Comment by JiyaGupta-cs** [comment]
Add two sections
Women at top then a button to explore more women category which would redirect it to the women products page which is already made
Then the men section and then the button likewise

**Comment by JiyaGupta-cs** [comment]
@Bishal-35 Any update?

**Comment by Bishal-35** [comment]
Working on it

**Pull request closed without merging**
